# Generated by Django 2.1.4 on 2019-06-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_auto_20190629_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
